### ISSUE TITLE
md5sum does not match the original PolarisBiosEditor 1.6.7

### ISSUE THREAD

**Issue by sponix** [vanities/PolarisBiosEditor-1.6.7#1]
When downloaded the md5sum does not match the original PolarisBiosEditor 1.6.7
And neither does the executable inside the git pull
Why has this been altered and placed online to impersonate the original ?

This is weird, because when I do the ./build.sh and the build completes, THEN the md5sum matches the original unaltered PolarisBiosEditor.exe  Please get to the bottom of this and correct the issue.

**Comment by vanities** [comment]
I did this so I could steal your LINK, lmao. I re-uploaded this after seeing the original one taken down and don't care to change the md5sum, especially if you have the original. I haven't made alterations, other than copying everything from the original INCLUDING the executable and pushing it to this repository.

Hot Tip: there's a button that says fork on it to the top right, better yet, make a PR to fix this issue.
